CREATE DATABASE Customer_Shopping;
USE Customer_Shopping;

CREATE TABLE Customer_Shopping_Behavior (
    customer_id INT PRIMARY KEY,
    age INT NOT NULL,
    gender VARCHAR(10) NOT NULL,
    item_purchased VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    purchase_amount DECIMAL(10,2) NOT NULL,
    location VARCHAR(100) NOT NULL,
    size VARCHAR(10) NOT NULL,
    color VARCHAR(30) NOT NULL,
    season VARCHAR(20) NOT NULL,
    review_rating DECIMAL(3,1) NOT NULL,
    subscription_status VARCHAR(10) NOT NULL,
    shipping_type VARCHAR(50) NOT NULL,
    discount_applied VARCHAR(10) NOT NULL,
    previous_purchases INT NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    frequency_of_purchases VARCHAR(50) NOT NULL,
    Purchase_Frequency_Days INT NOT NULL
);
SELECT * FROM Customer_Shopping_Behavior;


--Q1. What is the total revenue generated by male vs. female customers?
Select gender, SUM(purchase_amount) as Revenue
from Customer_Shopping_Behavior
group by gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
Select customer_id, purchase_amount
from Customer_Shopping_Behavior
where purchase_amount>=(Select avg(purchase_amount) from Customer_Shopping_Behavior) AND discount_applied = 'Yes';


-- Q3. Which are the top 5 products with the highest average review rating?
Select top 5 item_purchased,category, AVG(review_rating) as avg_rating
from Customer_Shopping_Behavior
group by item_purchased,category
order by avg_rating desc;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,AVG(purchase_amount) as avg_purchase
from Customer_Shopping_Behavior
where shipping_type in ('Standard','Express')
group by shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,count(customer_id),AVG(purchase_amount) as avg_spend, sum(purchase_amount) as total_revenue
from Customer_Shopping_Behavior
group by subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5item_purchased,ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ COUNT(*),2) AS Discount_Rate
FROM Customer_Shopping_Behavior
GROUP BY item_purchased
ORDER BY Discount_Rate DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM Customer_Shopping_Behavior)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (SELECT category,item_purchased,COUNT(customer_id) AS total_orders,ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM Customer_Shopping_Behavior
GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,COUNT(customer_id) AS repeat_buyers
FROM Customer_Shopping_Behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT
CASE
    WHEN age BETWEEN 18 AND 30 THEN '18-30'
    WHEN age BETWEEN 31 AND 45 THEN '31-45'
    WHEN age BETWEEN 46 AND 60 THEN '46-60'
    ELSE '61+'
END AS Age_Group,
SUM(purchase_amount) AS Total_Revenue
FROM Customer_Shopping_Behavior
GROUP BY
CASE
    WHEN age BETWEEN 18 AND 30 THEN '18-30'
    WHEN age BETWEEN 31 AND 45 THEN '31-45'
    WHEN age BETWEEN 46 AND 60 THEN '46-60'
    ELSE '61+'
END
ORDER BY Total_Revenue DESC;